# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.define "devstack" do |config|
    config.vm.hostname = "devstack"
    config.vm.provision "shell", path: "setup.sh", privileged: false
    config.vm.network :private_network, ip: "192.168.1.2"
    config.vm.provider :virtualbox do |vb|
      #vb.memory = 8192
      vb.customize ["modifyvm", :id, "--memory", 8192]
      vb.customize ["modifyvm", :id, "--cpus", 4]
      vb.customize "post-boot",["controlvm", :id, "setlinkstate1", "on"]
    end
  end

end
