#!/usr/bin/python

import etcd
import json
import re
import time

c = etcd.Client(host='localhost', port=2379)

tick = 0

def dump_result(w):
    print '%s [%s] %s %s(modified %s)' % \
            (time.strftime("%H:%M:%S"),
            w.action or 'read-all', w.key, 
            ('ttl = %s ' % str(w.ttl) if w.ttl is not None else ''),
            w.modifiedIndex)
    try:
        val = json.loads(w.value)
        out= json.dumps(val, indent=4)
        print ' > ', re.sub("\n", "\n >  ", out)
    except Exception as e:
        print ' > ', w.value

tick = 0
while True:
    res = c.read('/', recursive=True, index=tick)
    for w in res.children:
        dump_result(w)
    tick=res.etcd_index+1

    try:
        while True:
            w = c.watch('/', recursive=True, index=tick)
            dump_result(w)
            tick = w.modifiedIndex+1
    except etcd.EtcdException:
        # out of history
        pass

#        <class 'etcd.EtcdResult'>({'newKey': False, 'raft_index': 1728503, '_children': [], 'createdIndex': 469291, 'modifiedIndex': 469291, 'value': u'1', 'etcd_index': 469290, 'expiration': None, 'key': u'/a', 'ttl': None, 'action': u'set', 'dir': False})
